# Generated by Django 4.2.4 on 2023-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='numero_mesa',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='mesa',
            name='disponibilidad_mesa',
            field=models.BooleanField(default=True),
        ),
    ]
